// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Package manifests holds the Kubernetes manifests the Nirvati Init UI applies
// to a freshly bootstrapped single-node cluster.
package manifests

import _ "embed"

// CiliumYAML is a pre-rendered Cilium install manifest (helm template output,
// pinned chart version - see the command below to regenerate at a newer version):
//
//	helm repo add cilium https://helm.cilium.io/ && helm repo update
//	helm template cilium cilium/cilium --version 1.19.6 --namespace kube-system \
//	  --set ipam.mode=kubernetes --set kubeProxyReplacement=true \
//	  --set k8sServiceHost=localhost --set k8sServicePort=7445 \
//	  --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
//	  --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
//	  --set cgroup.autoMount.enabled=false --set cgroup.hostRoot=/sys/fs/cgroup
//
//go:embed cilium.yaml
var CiliumYAML string

// TraefikYAML is a pre-rendered Traefik install manifest (helm template output, pinned chart
// version - see the command below to regenerate at a newer version). It runs as a DaemonSet
// with hostNetwork so it answers directly on ports 80/443 on every node - important once a
// setup grows beyond a single node, since a plain Deployment would only bind those ports on
// whichever one node its single replica happened to land on:
//
//	helm repo add traefik https://traefik.github.io/charts && helm repo update
//	helm template traefik traefik/traefik --version 41.0.2 --namespace traefik --include-crds \
//	  --set deployment.kind=DaemonSet --set hostNetwork=true \
//	  --set deployment.dnsPolicy=ClusterFirstWithHostNet \
//	  --set ports.web.port=80 --set ports.websecure.port=443 \
//	  --set service.spec.type=ClusterIP \
//	  --set updateStrategy.rollingUpdate.maxUnavailable=1
//
//go:embed traefik.yaml
var TraefikYAML string

// NirvatiInitYAML is the Nirvati init Job manifest applied on new single-node clusters.
//
//go:embed nirvati-init.yaml
var NirvatiInitYAML string

// AutoBootstrapMarkerName is the inline manifest name used to mark configs generated by the
// "set up a new server" wizard as safe for AutoBootstrapController to automatically bootstrap.
const AutoBootstrapMarkerName = "nirvati-auto-bootstrap"

// AutoBootstrapMarkerYAML is an inert manifest applied purely as a marker - see AutoBootstrapMarkerName.
//
//go:embed auto_bootstrap_marker.yaml
var AutoBootstrapMarkerYAML string
