apiVersion: v1
kind: Namespace
metadata:
  name: system

---

apiVersion: v1
kind: Namespace
metadata:
  name: nirvati

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: full-access
  namespace: nirvati

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: full-access
  namespace: nirvati
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: full-access
  namespace: nirvati

---

apiVersion: batch/v1
kind: Job

metadata:
  name: init
  namespace: nirvati

spec:
  completions: 1
  backoffLimit: 1000
  #ttlSecondsAfterFinished: 1
  template:
    spec:
      hostNetwork: true
      restartPolicy: OnFailure
      serviceAccountName: full-access
      dnsPolicy: "ClusterFirst"
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: init
          image: dev-registry.nirvati.de/nirvati/init:main
          imagePullPolicy: IfNotPresent
          command:
            - /nirvati-init
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: host-root
              mountPath: /host-root
            - name: host-citadel
              mountPath: /citadel
          securityContext:
            privileged: true
          env:
            - name: STORAGE_LAYER
              value: v1
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_LOG
              value: debug
            - name: NIRVATI_APP_STORE_VERSION
              value: stable
            - name: DBUS_SYSTEM_BUS_ADDRESS
              value: /host-root/var/run/dbus/system_bus_socket
            - name: JWT_PUBKEY
              value: "PLACEHOLDER"
            - name: JWT_PUBKEY_BASE64
              value: "PLACEHOLDER"
            - name: KUBERNETES_SERVICE_HOST
              value: localhost
            - name: KUBERNETES_SERVICE_PORT
              value: "6443"
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: host-root
          hostPath:
            path: /
