// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package runtime

import (
	"context"
	"fmt"
	"net/netip"
	"net/url"
	"os"

	"github.com/cosi-project/runtime/pkg/controller"
	"github.com/cosi-project/runtime/pkg/safe"
	"github.com/cosi-project/runtime/pkg/state"
	"github.com/siderolabs/gen/optional"
	"go.uber.org/zap"

	machinedruntime "github.com/siderolabs/talos/internal/app/machined/pkg/runtime"
	"github.com/siderolabs/talos/internal/app/machined/pkg/system/services"
	machineapi "github.com/siderolabs/talos/pkg/machinery/api/machine"
	configconfig "github.com/siderolabs/talos/pkg/machinery/config/config"
	"github.com/siderolabs/talos/pkg/machinery/config/machine"
	"github.com/siderolabs/talos/pkg/machinery/constants"
	configresource "github.com/siderolabs/talos/pkg/machinery/resources/config"
	"github.com/siderolabs/talos/pkg/machinery/resources/network"
	"github.com/siderolabs/talos/pkg/maintenanceweb/manifests"
)

// AutoBootstrapController automatically bootstraps etcd, exactly once, on a control plane node
// whose applied config was generated by the Nirvati Init UI's "set up a new server" wizard
// (internal/app/machined/pkg/controllers/runtime/maintenance_web_configgen.go) for a
// self-hosted single-node cluster.
//
// It exists because applying such a config triggers Talos's own install-to-disk + reboot
// sequence, by which point the maintenance web server that generated the config is long gone -
// so nothing else is left to trigger etcd bootstrap. Unlike the maintenance web server, this
// controller is registered unconditionally and runs on every boot, including workers and nodes
// from unrelated/foreign clusters, so it must be conservative: see gate() for the full set of
// conditions required before it will ever call BootstrapEtcd.
type AutoBootstrapController struct {
	V1Alpha1Runtime machinedruntime.Runtime

	bootstrapped bool
}

// Name implements controller.Controller interface.
func (ctrl *AutoBootstrapController) Name() string {
	return "runtime.AutoBootstrapController"
}

// Inputs implements controller.Controller interface.
func (ctrl *AutoBootstrapController) Inputs() []controller.Input {
	return []controller.Input{
		{
			Namespace: configresource.NamespaceName,
			Type:      configresource.MachineConfigType,
			ID:        optional.Some(configresource.ActiveID),
			Kind:      controller.InputWeak,
		},
		{
			Namespace: network.NamespaceName,
			Type:      network.NodeAddressType,
			ID:        optional.Some(network.NodeAddressCurrentID),
			Kind:      controller.InputWeak,
		},
	}
}

// Outputs implements controller.Controller interface.
func (ctrl *AutoBootstrapController) Outputs() []controller.Output {
	return nil
}

// Run implements controller.Controller interface.
func (ctrl *AutoBootstrapController) Run(ctx context.Context, r controller.Runtime, logger *zap.Logger) error {
	for {
		select {
		case <-ctx.Done():
			return nil
		case <-r.EventCh():
		}

		if !ctrl.bootstrapped {
			ok, err := ctrl.maybeBootstrap(ctx, r, logger)
			if err != nil {
				return err
			}

			ctrl.bootstrapped = ok
		}

		r.ResetRestartBackoff()
	}
}

func (ctrl *AutoBootstrapController) maybeBootstrap(ctx context.Context, r controller.Runtime, logger *zap.Logger) (bool, error) {
	shouldBootstrap, err := ctrl.gate(ctx, r)
	if err != nil || !shouldBootstrap {
		return false, err
	}

	// Replicate the etcd-data-dir-empty check the Bootstrap gRPC handler does *before* calling
	// the bootstrapper (v1alpha1_server.go), rather than relying on BootstrapEtcd's own internal
	// check: BootstrapEtcd stops the running etcd service first and only checks emptiness
	// afterwards, so calling it blindly on an already-bootstrapped node would stop a healthy
	// running etcd out from under it before cleanly failing.
	empty, err := etcdDataDirEmpty()
	if err != nil {
		return false, fmt.Errorf("failed to check etcd data directory: %w", err)
	}

	if !empty {
		// already bootstrapped in a previous boot - nothing to do, and safe to stop reconciling.
		return true, nil
	}

	logger.Info("auto-bootstrapping single-node cluster")

	if err := services.BootstrapEtcd(ctx, ctrl.V1Alpha1Runtime, &machineapi.BootstrapRequest{}); err != nil {
		return false, fmt.Errorf("failed to auto-bootstrap etcd: %w", err)
	}

	return true, nil
}

// gate reports whether this node's applied config makes it safe to automatically bootstrap etcd.
// All conditions must hold; see the AutoBootstrapController doc comment for why this must be
// conservative.
func (ctrl *AutoBootstrapController) gate(ctx context.Context, r controller.Runtime) (bool, error) {
	cfg, err := safe.ReaderGetByID[*configresource.MachineConfig](ctx, r, configresource.ActiveID)
	if err != nil {
		if state.IsNotFoundError(err) {
			return false, nil
		}

		return false, fmt.Errorf("failed to get machine config: %w", err)
	}

	provider := cfg.Provider()
	if provider == nil || provider.Machine() == nil || provider.Machine().Type() != machine.TypeControlPlane {
		return false, nil
	}

	if !hasAutoBootstrapMarker(provider.K8sInlineManifestConfigs()) {
		return false, nil
	}

	selfHosted, err := ctrl.endpointIsSelf(ctx, r, provider.K8sClusterConfig().ClusterEndpoint())
	if err != nil || !selfHosted {
		return false, err
	}

	return ctrl.V1Alpha1Runtime.IsBootstrapAllowed(), nil
}

func hasAutoBootstrapMarker(inlineManifests []configconfig.K8sInlineManifestConfig) bool {
	for _, m := range inlineManifests {
		if m.Name() == manifests.AutoBootstrapMarkerName {
			return true
		}
	}

	return false
}

// endpointIsSelf reports whether endpoint's host is a literal IP address (never a DNS name - see
// the AutoBootstrapController doc comment, this wizard only ever generates literal-IP endpoints,
// and we fail closed for anything else) matching one of this node's own current addresses.
func (ctrl *AutoBootstrapController) endpointIsSelf(ctx context.Context, r controller.Runtime, endpoint *url.URL) (bool, error) {
	if endpoint == nil {
		return false, nil
	}

	endpointIP, err := netip.ParseAddr(endpoint.Hostname())
	if err != nil {
		// not a literal IP (e.g. a DNS name or load balancer address) - fail closed.
		return false, nil
	}

	nodeAddress, err := safe.ReaderGetByID[*network.NodeAddress](ctx, r, network.NodeAddressCurrentID)
	if err != nil {
		if state.IsNotFoundError(err) {
			return false, nil
		}

		return false, fmt.Errorf("failed to get node address: %w", err)
	}

	return matchesNodeAddress(endpointIP, nodeAddress.TypedSpec().IPs()), nil
}

// matchesNodeAddress reports whether endpointIP is one of ips, ignoring SideroLink addresses.
func matchesNodeAddress(endpointIP netip.Addr, ips []netip.Addr) bool {
	for _, ip := range ips {
		if network.NotSideroLinkIP(ip) && ip == endpointIP {
			return true
		}
	}

	return false
}

func etcdDataDirEmpty() (bool, error) {
	entries, err := os.ReadDir(constants.EtcdDataPath)
	if err != nil {
		if os.IsNotExist(err) {
			return true, nil
		}

		return false, err
	}

	return len(entries) == 0, nil
}
